services:
  - type: web
    name: zepfly-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5000
      - key: JWT_SECRET
        generateValue: true
      - key: CLIENT_URL
        value: https://your-frontend-domain.com
