// Shared Tailwind typography, document defaults and accessible interaction states.
export const documentClasses = [
  "[font-family:Inter,_'Segoe_UI',_Arial,_sans-serif] text-[#1e293b] bg-white",
  '[font-synthesis:none] [text-rendering:optimizeLegibility]',
  '[-webkit-font-smoothing:antialiased] font-normal scroll-smooth scroll-pt-[100px]',
  'selection:bg-[#dce9ff] motion-reduce:scroll-auto motion-reduce:[&_*]:transition-none!',
  'motion-reduce:[&_*]:animate-none! motion-reduce:[&_*::before]:transition-none!',
  'motion-reduce:[&_*::before]:animate-none! motion-reduce:[&_*::after]:transition-none!',
  'motion-reduce:[&_*::after]:animate-none! [:where(&_body)]:m-0',
  '[:where(&_button)]:[font:inherit]',
  '[:where(&_button)]:[-webkit-tap-highlight-color:transparent]',
  '[:where(&_button)]:touch-manipulation [:where(&_button)]:cursor-pointer',
  '[:where(&_button:disabled)]:cursor-default',
  '[:where(&_button)]:[transition:background_0.18s,_color_0.18s,_box-shadow_0.18s,_transform_0.18s]',
  '[:where(&_button:focus-visible)]:[outline:3px_solid_#7c3aed]',
  '[:where(&_button:focus-visible)]:[outline-offset:4px] [:where(&_input)]:[font:inherit]',
  '[:where(&_input)]:[-webkit-tap-highlight-color:transparent]',
  '[:where(&_input:focus-visible)]:[outline:3px_solid_#7c3aed]',
  '[:where(&_input:focus-visible)]:[outline-offset:4px] [:where(&_select)]:[font:inherit]',
  '[:where(&_select)]:[-webkit-tap-highlight-color:transparent]',
  '[:where(&_select:focus-visible)]:[outline:3px_solid_#7c3aed]',
  '[:where(&_select:focus-visible)]:[outline-offset:4px] [:where(&_textarea)]:[font:inherit]',
  '[:where(&_textarea)]:[-webkit-tap-highlight-color:transparent]',
  '[:where(&_textarea:focus-visible)]:[outline:3px_solid_#7c3aed]',
  '[:where(&_textarea:focus-visible)]:[outline-offset:4px]',
  '[:where(&_a)]:[-webkit-tap-highlight-color:transparent] [:where(&_a)]:touch-manipulation',
  '[:where(&_a)]:text-[inherit] [:where(&_a)]:no-underline',
  '[:where(&_a)]:[transition:background_0.18s,_color_0.18s,_box-shadow_0.18s,_transform_0.18s]',
  '[:where(&_a:focus-visible)]:[outline:3px_solid_#7c3aed]',
  '[:where(&_a:focus-visible)]:[outline-offset:4px] [:where(&_h1)]:m-0',
  '[:where(&_h1)]:text-[#102a43] [:where(&_h1)]:text-[clamp(40px,_4.25vw,_60px)]',
  '[:where(&_h1)]:leading-[1.14] [:where(&_h1)]:tracking-[-2.5px] [:where(&_h1)]:font-[650]',
  'max-[720px]:[:where(&_h1)]:tracking-[-1.7px] [:where(&_h2)]:m-0 [:where(&_h2)]:text-[#102a43]',
  '[:where(&_h2)]:text-[clamp(28px,_2.7vw,_38px)] [:where(&_h2)]:leading-[1.25]',
  '[:where(&_h2)]:tracking-[-1.2px] [:where(&_h2)]:font-[650] [:where(&_h3)]:m-0',
  '[:where(&_h3)]:text-[#102a43] [:where(&_h3)]:font-semibold [:where(&_h3)]:text-[18px]',
  '[:where(&_h3)]:leading-[1.45] [:where(&_h3)]:tracking-[-0.35px] [:where(&_p)]:m-0',
  '[:where(&_p)]:text-[15px] [:where(&_p)]:leading-[1.8] [:where(&_p)]:text-[#64748b]',
  '[:where(&_svg)]:shrink-0',
].join(' ');
